baseurl = "https://www.grenmester.com/"
title = "Jacky Lee"
languageCode = "en-us"
paginate = "10"
theme = "Mainroad"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/about/projects"
    weight = 2
  [[menu.main]]
    name = "Course Notes"
    url = "/about/course-notes"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.footer]]
    name = "About This Website"
    url = "/about"
    weight = 2
  [[menu.footer]]
    name = "About Me"
    url = "/about/about-me"
    weight = 3

[Params]
  subtitle = "My Personal Website"
  description = "Jacky Lee's personal website"
  readmore = true
  post_meta = ["date", "categories"]
  mainSections = "post"

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5

[Params.widgets.social]
  linkedin = "grenmester"
  github = "grenmester"
  email = "grenmester@gmail.com"
