baseurl = "https://www.grenmester.com/"
title = "Jacky Lee"
languageCode = "en-us"
paginate = "10"
theme = "Mainroad"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[Params]
  subtitle = "My Personal Website"
  description = "Jacky Lee's personal website"
  readmore = true
  homeLayout = "content + sidebar"
  listLayout = "content + sidebar"
  singleLayout = "content + sidebar"
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"

[Params.widgets]
  search = true
  recent_articles = true
  recent_articles_num = 5
  categories = true
  tags = true
  tags_counter = true
  social_linkedin = "grenmester"
  social_github = "grenmester"
  social_email = "grenmester@gmail.com"

[Taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
